#### What is cost function : it is function that measure performance of any model for a given data

#### What is Gradient Descent?
* Gradient descent is an optimization algorithm used in machine learning to minimize the cost function by iteratively adjusting parameters in the direction of the negative gradient, aiming to find the optimal set of parameters.
* ![nn.png](nn.png)
* [gradient](1_Y2RjvgGkisVM1Q4N4U5Uzg.webp)

### Implement Gradient Descent For Neural Network (or Logistic Regression)
Predicting if a person would buy life insurnace based on his age using logistic regression
Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't).

In [59]:
import pandas as pd
import numpy as np

In [61]:
insurence = pd.read_csv("insurance_data.csv")

In [63]:
insurence

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    insurence[["age","affordibility"]] , insurence["bought_insurance"], 
    test_size=0.2,       # 20% for testing
    random_state=42,     # for reproducibility
    shuffle=True          # shuffle before splitting (default=True)
)

In [67]:
X_train.head()

age  affordibility
17   58              1
22   40              1
11   28              1
13   29              0
15   55              1

In [73]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [77]:
X_train_scaled

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

### First made nural model to see weights and bias and after reproduce it wit gradient decent

In [111]:
import tensorflow as tf
from tensorflow import keras
import math

In [127]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid')
])
model.compile(
              optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
)

model.fit(X_train_scaled, y_train, epochs=1100)
    

Epoch 1/1100


C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 543ms/step - accuracy: 0.6364 - loss: 0.7141
Epoch 2/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6364 - loss: 0.7140
Epoch 3/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6364 - loss: 0.7139
Epoch 4/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6364 - loss: 0.7138
Epoch 5/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6364 - loss: 0.7137
Epoch 6/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6364 - loss: 0.7136
Epoch 7/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6364 - loss: 0.7135
Epoch 8/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6364 - loss: 0.7134
Epoch 9/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6364 - loss: 0.7133
Epoch 10/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.6364 - loss: 0.7132
Epoch 11/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6364 - loss: 0.7131
Epoch 12/1100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6364 - l

In [129]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.8333 - loss: 0.5404


[0.540414571762085, 0.8333333134651184]

In [131]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[0.5962274 ],
       [0.59728277],
       [0.5960766 ],
       [0.31997812],
       [0.6020956 ],
       [0.31984183]], dtype=float32)

In [133]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

In [135]:
w, b = model.get_weights()

In [137]:
w,b

(array([[-0.06265091],
        [ 1.1655706 ]], dtype=float32),
 array([-0.7375831], dtype=float32))

### This means weights are w1=-0.06265091, w2=1.1655706  and bias= -0.7375831

* Now we can predicts by calculating with values of weights and bias

In [145]:
def sigmoid(x):
    return 1/(1+math.exp(-x))
sigmoid(-3)

0.04742587317756678

In [155]:
def prediction(age, afordability):
    weighted_sum = -0.06265091*age+1.1655706*afordability+-0.7375831
    return sigmoid(weighted_sum)

In [149]:
X_test_scaled

age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [163]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

In [159]:
prediction(0.61, 1)

0.5962274373586208

In [161]:
prediction(0.26, 0)

0.31997812414882765

In [182]:
prediction(0.62, 1)

0.5960766022937618